export const SET_KEPLR_ENABLED = `SET_KEPLR_ENABLED`;
export const SET_SCRT_AUTHORIZED = `SET_SCRT_AUTHORIZED`;
export const SET_SECRET_CLIENT = `SET_SECRET_CLIENT`;
export const SET_VIEWING_KEY = `SET_VIEWING_KEY`;
export const SET_LOGGED_IN = `SET_LOGGED_IN`;

export const SET_HANDLE_SEARCH_FIELD_VALUE = `SET_HANDLE_SEARCH_FIELD_VALUE`;
export const SET_DRAWER_MENU_SELECTION = `SET_DRAWER_MENU_SELECTION`;
export const SET_FARDEL_VIEW_DIALOG_OPEN = `SET_FARDEL_VIEW_DIALOG_OPEN`;

// View handle
export const SET_VIEWED_HANDLE = `SET_VIEWED_HANDLE`;
export const SET_VIEWED_HANDLE_IMG = `SET_VIEWED_HANDLE_IMG`;
export const SET_VIEWED_FARDELS = `SET_VIEWED_FARDELS`;
export const SET_SELECTED_FARDEL = `SET_SELECTED_FARDEL`;

// Following
export const SET_FOLLOWING = `SET_FOLLOWING`;

// My Fardels
export const SET_NEW_FARDEL_MESSAGE = `SET_NEW_FARDEL_MESSAGE`;
export const SET_NEW_FARDEL_CONTENTS = `SET_NEW_FARDEL_CONTENTS`;
export const SET_NEW_FARDEL_THUMBNAIL = `SET_NEW_FARDEL_THUMBNAIL`;
export const CLEAR_NEW_FARDEL = `CLEAR_NEW_FARDEL`;
export const SET_MY_FARDELS = `SET_MY_FARDELS`;

// Profile
export const SET_HANDLE = `SET_HANDLE`;
export const SET_PROFILE_DESCRIPTION = `SET_PROFILE_DESCRIPTION`;
export const SET_PROFILE_THUMBNAIL = `SET_PROFILE_THUMBNAIL`;